### ISSUE TITLE
Add flag that allows advanced queries

### ISSUE THREAD

**Issue by kauffj** [lbryio/lighthouse#104]
I believe https://github.com/lbryio/lighthouse/pull/103 effectively turns off advanced query functionality. I think this is a fine choice since it makes search work without issues with no app-side changes required.

However, it may make sense to add a flag like `no_escape=1` or `advanced=1` so that these features can still be used if desired.

Please close if I misunderstood effect of #103.

**Comment by tiger5226** [comment]
They could not be used before this because we are using the wild cards `* + s.input() + *`, which is why it was misinterpreted to begin with causing the 400 BadRequest. Also the query_string is just 1 part of the overall query. Attempting to use advanced query functionality would not really work even if we did not use the wildcards in this manner as the rest of the queries leveraged do not use query_string.
