### ISSUE TITLE
bad request returned on certain searches

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lighthouse#112]
Examples:
https://lighthouse.lbry.io/search?s=Mar%20GamingYT%20%20%20Robux%20Simulator%20/%20REBIRTH!&size=20&from=0

https://lighthouse.lbry.io/search?s=Mar%20GamingYT%20%20%20Baldi%20Obby!%20/%20I%20got%20lost,%20but%20won!&size=20&from=0

Might be related to some special characters?

**Comment by tzarebczan** [comment]
Another: 
https://lighthouse.lbry.io/search?s=Playing%20Robloxian%20Life%20%20w%20god39lol/%20Mar%20GamingYT&size=20&from=0

**Comment by tiger5226** [comment]
The problem is the url is not properly encoded. Forward slash when url encoded should be `%2F`. I think this is the right response when the api receive a malformed url.

https://lighthouse.lbry.io/search?s=Mar%20GamingYT%20%20%20RobuxSimulator%20%2F%20REBIRTH

The above is an example where it should work though and does not. The forward slash seems to cause problems so how.

**Comment by tiger5226** [comment]
So I found some more documentation on the escaped characters. Some pages had different characters to escape. I found the official documentation on escaped characters. I noted it in the codebase for reference. 

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_reserved_characters

Solved with https://github.com/lbryio/lighthouse/pull/115
