### ISSUE TITLE
Search result affected by a number at end of title

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lighthouse#119]
This query for `AdmiralBulldog Bristleback Aghanim's [YOU CAN'T RUN!] Dota 2`  https://lighthouse.lbry.io/search?s=AdmiralBulldog%20Bristleback%20Aghanim%27s%20%5BYOU%20CAN%27T%20RUN!%5D%20Dota%202&size=20&from=0 - brings in high effective amount claims like one, four, six at the top fo the list

Removing the 2 at the end `AdmiralBulldog Bristleback Aghanim's [YOU CAN'T RUN!] Dota`:
https://lighthouse.lbry.io/search?s=AdmiralBulldog%20Bristleback%20Aghanim%27s%20%5BYOU%20CAN%27T%20RUN!%5D%20Dota%20&size=20&from=0 - brings better results (lbry://three is up there because of `you` most likely - probably need to blacklist that word. 

Not sure what other instances of numbers would affect query results but it may be worth digging into.

**Comment by tiger5226** [comment]
we can blacklist numbers via a cast check. @nikooo777 is that performant in js or is there something else you would recommend?

**Comment by nikooo777** [comment]
why is the number affecting the results? aren't sequences of less than 3 chars ignored?

**Comment by tiger5226** [comment]
ahhh thats a good point niko! I will have to check the code to see if any part of the query is not being washed properly.

**Comment by marcdeb1** [comment]
It seems that the after the query is washed, the result is "admiralbulldog bristleback aghanim'[you can'run!] dota". It is removing spaces that shouldn't be removed, for example it should be "you can't run". This is because of the regex.
Secondly, because of this, sometimes a trailing whitespace remains (when "2" is removed), this causes one of the queries to return all results (query_string with * wildcard). Because of the effective_amount score, top claims will appear first.
I will propose a PR to solve this issue.

**Comment by tiger5226** [comment]
Boom! nice investigation!

**Comment by tzarebczan** [comment]
https://github.com/lbryio/lighthouse/pull/125 did not fix this issue. Removing the 2 at the end still gives better results (without the top claims).

**Comment by tiger5226** [comment]
@tzarebczan I checked the server, and there was an issue with the update shell script. It was in dev but not production. production should be up to date again.

**Comment by alyssaoc** [comment]
closing, reopen when tom comes back from Japan
