### ISSUE TITLE
Search result missing - open-source-video-editing-lesson-4

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lighthouse#120]
When running https://lighthouse.lbry.io/search?s=open-source-video-editing-lesson-4&size=50&from=0

lbry://open-source-video-editing-lesson-4 is missing from the search results

**Comment by tiger5226** [comment]
@tzarebczan I see each of the lessons and agree that lesson 4 is missing. 

https://chainquery.lbry.io/api/sql?query=SELECT%20*%20FROM%20claim%20WHERE%20name%20=%22open-source-video-editing-lesson-4%22

Chainquery has it as expired which is why it would not show up in the search results. It shows in the app, so maybe there is a bug somewhere. 

https://github.com/lbryio/chainquery/issues/55

Moved to chainquery
