### ISSUE TITLE
Search for SwissExperiments doesn't return @Swiss-Experiments channel

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lighthouse#154]
`Swiss Experiments` does work. We should take into account the - when searching.

**Comment by tiger5226** [comment]
This is an interesting one. We can't really know that `SwissExperiments` should be split into `Swiss Experiments`. Elastic search does already recognize the `-` and will treat it as 2 words. Also our query will escape the reserved character so the actual text `Swiss-Experiments` will work fine due to the sloppy factor. Searching for `Swiss` or `Experiments` will also work fine because elastic search splits automatically on the `-`. 

One possible solution is to take any claim name and remove any `-` and collapse the string into another field in the elastic document that is equally weighted to the current name field. 

I am also open to other ideas here too if you have any.

**Comment by tiger5226** [comment]
This is now fixed with the latest push to master. We have removed query washing for phrase matching and partial string comparison.
