### ISSUE TITLE
Define search API

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lighthouse#16]
The motivation for this issue is to standardize and document how the app makes search requests and what structure the returned data must have. By defining the API, we allow others to run their own search servers.

# Proposed Definition

## Protocol

Search requests and responses will be made over HTTP.

## Request

Search requests will be made to `/search` endpoint using GET parameters. 

The `s` get parameter will contain the search query. 

No other parameters are defined. Search servers may accept and respond to extra parameters.

## Response

The response must be a JSON array of objects. Each object must have the following fields:

- `claimId`: the ID of a claim (in hex)
- `name`: the name of the claim

### Request
```
https://lighthouse.lbry.com/search?s=LBRY%20is%20quickly%20gaining%20adoption
```

### Response
```
[
  {
    "claimId": "ce9287d1cb89b8fae83b86fd1822bc350daa2a4f",
    "name": "always-quickly-quickly"
  },
  {
    "claimId": "1ece088da21e327531cd815fd11ae7062f4482fe",
    "name": "how-quickly-is-mgtow-growing"
  },
  {
    "claimId": "e4ce72ae3568d0d0bc9e54336a2b05b056796189",
    "name": "chill-jazzy-beat-quickly-quickly-hushed"
  }
]
```

**Comment by tiger5226** [comment]
https://github.com/lbryio/lighthouse/blob/75eb583ed68058d2b0af9d71b969baffa8bea2a6/app/actions/search/search.go#L19-L36

Everything above debug params is part of the API. See my note about updating the api too, since we are defining it.

**Comment by lyoshenka** [comment]
is this the next version of the api? i dont see any of those fields in the current search results.

which of those fields are required? they're all pointers, so they're all optional?

**Comment by jessopb** [comment]
If possible, please include "Duration", which could be audio or video duration (separate in chainquery, it seems).

**Comment by tiger5226** [comment]
@lyoshenka those are input parameters that the app uses. The debug ones are not used by the app. Yes the pointers are ones that are optional. 

@jessopb I have that information in there now. we can filter on duration now if we added it. I never got clarification from you on what you wanted. Can you explain? 

if its sorting we should add a drop dropdown in the app for `relevance`, `age`,`duration`, `cost` etc. So users know what they are asking search to prioritize. If we try to do it in the background its a bad user experience because they dont really know why the see certain results. If want to see the newest related content, it might not be the most relevant to my search. This is ok if its my intention and the dropdown allows for the selection of intent. I would also help us to determine what people care about most and we can weight our default that way.

**Comment by lyoshenka** [comment]
@eukreign bringing this to your attention since you said you're thinking about it

**Comment by eukreign** [comment]
it's defined here: https://github.com/lbryio/lbry-sdk/issues/2855

**Comment by lyoshenka** [comment]
Closing in favor of https://github.com/lbryio/lbry-sdk/issues/2855
