### ISSUE TITLE
Return claim title in autocomplete results (along with claim name)

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lighthouse#28]
So we can display the title in the search dropdown, and still link to the file page

**Comment by seanyesmunt** [comment]
Please also include the channel name on it's own too

**Comment by tzarebczan** [comment]
So like https://lighthouse.lbry.com/search?s=jiggytom&resolve=true but for autocomplete api right?

**Comment by seanyesmunt** [comment]
Hm. That's a good point. Maybe we should just drop the autocomplete API and use search for this too? @tiger5226 any reason not to do this?

**Comment by tiger5226** [comment]
Yeah, autocomplete is a different search all together. Its HIGHLY optimized to be super fast, because it returns as you type. We can add those additional fields for sure like Tom is suggesting. I think it would be good. The auto complete only really works with claim names right now which super legacy. adding the resolve param to the api should give you what you need.

**Comment by kauffj** [comment]
Also, return image/channel, everything necessary to show a small card/result.
