### ISSUE TITLE
Need exact title in the search to find a video

### ISSUE THREAD

**Issue by affa85** [lbryio/lighthouse#50]
I tested on my videos that all starts with "Gjerrigveganerens", if i dropped the s in the ending of the word, then i couldn't find any of my videos

**Comment by tiger5226** [comment]
Should be fixed by #54

**Comment by tiger5226** [comment]
Thanks for reporting the issue! This was caused by converting to match query from a contains query. In order to enhance our search capabilities we changed the query to leverage a nested query to get relevant information from the Author,Title,Description fields of a claim ( previously unsearchable ). The default query to use inside of a nested query is the match. 

This has now been adjusted so we get the best of both worlds. I also added phrase matching in case multi-word searches are used.

Should be fixed by #54

**Comment by tiger5226** [comment]
This is now corrected with the latest deployment of lighthouse.
